config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  controllers: { registrations: 'registrations' }
  resources :tweeets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweeets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
    validates :tweeet, presence: true, allow_blank: false
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
      
  has_many :tweeets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController

  private

	def sign_up_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
	end

	def account_update_params 
		params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
	end
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tweeets
  # GET /tweeets.json
  def index
    @tweeets = Tweeet.all.order("created_at DESC")
    @tweeet = Tweeet.new
    @users = User.all.sample(5)
  end

  # GET /tweeets/1
  # GET /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets
  # POST /tweeets.json
  def create
    @tweeet = current_user.tweeets.build(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to root_path, notice: 'Tweeet was successfully created.' }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1
  # PATCH/PUT /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: 'Tweeet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1
  # DELETE /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: 'Tweeet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.5.1.slim.min.js", integrity: "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj", crossorigin: "anonymous" %>       
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js", integrity: "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo", crossorigin: "anonymous" %>
    <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js", integrity: "sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI", crossorigin: "anonymous" %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="alert alert-info mb-0" role="alert">
        <p><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-warning mb-0" role="alert">
        <p><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="navbar-brand">
        <%= link_to root_path, class: "text-decoration-none" do %>
          <h1 class = "text-white">Twittter</h1>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in?%>
            <li class="nav-item active">
              <%= link_to 'New Tweeet', root_path, class: "btn btn-light text-primary mr-2" %>
            </li>
            <li class="nav-item">
                <%= link_to "Hi, #{current_user.name}!", edit_user_registration_path, class: "btn text-white" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path,method: :delete, class: "btn btn-danger" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-light text-primary mr-2 mt-1" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "btn btn-light text-primary mt-1" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  
    <%= yield %>
  </body>
</html>

app/views/tweeets/_feed.html.erb
<div class="col-md-6">
<h3 class = "text-center">Tweets</h3>
  <% if user_signed_in? %>
  <div class = "d-flex justify-content-center mb-5">
				<%= gravatar_image_tag(current_user.email, size: 64, class: "rounded-circle mr-2", alt: current_user.name) %>
			 <%= render 'tweeets/form' %>
	</div>
  <% end %>
  <% @tweeets.each do | tweeet | %>
    <div class="box">
  	<article class="media">
  		<div>
  			<figure>
  				<%= gravatar_image_tag(tweeet.user.email, size: 64, alt: tweeet.user.name, class: "rounded-circle mr-2") %>
  			</figure>
  		</div>
  		<div class="media-content">
  			<div class="content">
  				<strong><%= tweeet.user.name %></strong><br />
  				<small>@<%= tweeet.user.username %></small><br/>
  				<p><%= tweeet.tweeet %></p>
  			</div>
        <% if user_signed_in? && current_user.id == tweeet.user_id %>
  			<nav>
  				<div class="level-left is-mobile">
  					<%= link_to tweeet, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_tweeet_path(tweeet), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to tweeet, method: :delete, data: { confirm: "Are you sure you want to delete this tweeet?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
  			</nav>
        <% end %>
  		</div>
  	</article>
  </div>
    <% end %>
  </div>

app/views/tweeets/_form.html.erb
<%= form_with(model: @tweeet, local: true) do |form| %>
  <% if @tweeet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
        <% tweeet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_area :tweeet, class: "form-control", autofocus: true %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweeets/_profile.html.erb
<div class="col-md-3">
  <h3 class = "text-center">Profile</h3>
  <div class="media">
    <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name, class: "rounded-circle mr-2") %>
    <div class="media-body">
      <h5 class="mt-0"><%= current_user.name %></h5>
      <p>
        <small>@<%= current_user.username %></small>
      </p>
    </div>
  </div>
  <div class = "row ml-0 mt-2 table-responsive">
    <table class="table table-sm table-borderless">
      <thead>
        <tr>
          <th scope="col">Tweeets</th>
          <th scope="col">Following</th>
          <th scope="col">Followers</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= current_user.tweeets.count %></td>
          <td>100</td>
          <td>200</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/tweeets/_trends.html.erb
<div class="col-md-3">
	<nav class="nav nav-pills flex-column text-center">
		<a class="nav-link" href="#">Trend1</a>
		<a class="nav-link" href="#">Trend2</a>
		<a class="nav-link" href="#">Trend3</a>
		<a class="nav-link" href="#">Trend4</a>
		<a class="nav-link" href="#">Trend5</a>
		<a class="nav-link" href="#">Trend6</a>
	</nav>
</div>

app/views/tweeets/_who_to_follow.html.erb
<div class="col-md-3">
  <h3 class = "text-center">Who to follow</h3>
  <ul class="list-unstyled">
    <% if @users.size > 0 %>
      <% @users.each do|user|%>
      <li class="media mb-2">
        <%= gravatar_image_tag(user.email, size: 64, alt: user.name, class: "rounded-circle mr-2") %>
        <div class="media-body">
          <h5 class="mt-0 mb-1"><strong><%= user.name%></strong></h5>
          <small><%= user.username%></small>
        </div>
      </li>
    <% end%>
    <% else %>
      No users yet :(
    <% end %>
    
  </ul>
</div>

app/views/tweeets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweeet</h1>
				<%= render 'form', tweeet: @tweeet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweeets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweeets/index.html.erb
<section class="section">
  <div class="container">
    <div class="row">
    <% if user_signed_in? %>
    <%= render 'profile' %>
    <% else %>
    <%= render 'trends' %>
    <% end %>
      <%= render 'feed' %>
      <%= render 'who_to_follow' %>
    </div>
  </div>
</section>

app/views/tweeets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tweeet</h1>
					<%= render 'form', tweeet: @tweeet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', tweeets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>